export const dummyProfileData = {
	company: {
		id: 'comp001',
		name: 'Tech Innovators Inc.',
		email: 'contact@techinnovators.com',
		phone: '+1 555-123-4567',
		website: 'https://www.techinnovators.com',
		about: 'Leading the way in innovative tech solutions.',
		industry: 'Technology',
		address: {
			street: '123 Innovation Lane',
			city: 'San Francisco',
			state: 'CA',
			country: 'USA',
			postalCode: '94107',
		},
		establishedDate: '2001-03-15',
		size: '51-200 employees',
		logo: 'https://via.placeholder.com/150',
	},
	mentor: {
		id: 'ment001',
		name: 'Jane Doe',
		email: 'jane.doe@example.com',
		phone: '+1 555-987-6543',
		expertise: ['Web Development', 'Career Coaching', 'UI/UX Design'],
		bio: 'Experienced web developer and career mentor.',
		profilePicture: 'https://via.placeholder.com/150',
		availability: 'Available',
		linkedIn: 'https://linkedin.com/in/janedoe',
		location: {
			city: 'Los Angeles',
			state: 'CA',
			country: 'USA',
		},
		ratings: [
			{ studentId: 'stud001', rating: 4.8, comment: 'Amazing mentor!' },
			{
				studentId: 'stud002',
				rating: 4.5,
				comment: 'Very helpful and knowledgeable.',
			},
		],
	},
	student: {
		id: 'stud001',
		name: 'John Smith',
		email: 'john.smith@example.com',
		phone: '+1 555-789-0123',
		dateOfBirth: '1999-06-20',
		enrolledCourses: [
			{
				courseId: 'course001',
				courseName: 'Full-Stack Web Development',
				progress: 85,
				enrollmentDate: '2023-01-15',
			},
			{
				courseId: 'course002',
				courseName: 'UI/UX Design Basics',
				progress: 60,
				enrollmentDate: '2023-03-01',
			},
		],
		careerGoal: 'Become a full-stack developer.',
		profilePicture: 'https://via.placeholder.com/150',
		location: {
			city: 'Austin',
			state: 'TX',
			country: 'USA',
		},
		mentors: [{ mentorId: 'ment001', mentorName: 'Jane Doe' }],
	},
}
